image: node:6.11.4-alpine

stages:
  - build

before_script:
  - chmod +x gradlew

build:
  stage: build
  script: ./gradlew --build-cache build
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle
      - node_modules