image: node:6.11.4-alpine

stages:
  - build

build:
  stage: build
  script: npm run-script build
  artifacts:
    paths:
      - npm-debug.log
    when: on_failure
    expire_in: 1 month
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - node_modules